"""add type to transaction

Revision ID: 013c55fce6b3
Revises: 2ff024067811
Create Date: 2025-06-05 10:59:06.447747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

transaction_type_enum = sa.Enum('income', 'expense', name='transactiontype')

# revision identifiers, used by Alembic.
revision: str = '013c55fce6b3'
down_revision: Union[str, None] = '2ff024067811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    op.drop_index('ix_category_id', table_name='category')
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=True)
    op.add_column('transactions', sa.Column('type', sa.Enum('income', 'expense', name='transactiontype'), nullable=False))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    op.create_unique_constraint(None, 'transactions', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('transactions', 'type')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
