"""add created_at to transaction

Revision ID: 4f0a5f703772
Revises: 62cda9f7f6f1
Create Date: 2025-06-05 12:55:11.042303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0a5f703772'
down_revision: Union[str, None] = '62cda9f7f6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_category_title", "category", ["user_id", "title"])
    op.add_column('transactions',sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
