"""кadd user to category part 2

Revision ID: 62cda9f7f6f1
Revises: b64992f51c51
Create Date: 2025-06-05 12:25:02.722281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cda9f7f6f1'
down_revision: Union[str, None] = 'b64992f51c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_user_id_key', 'category', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_user_id_key', 'category', ['user_id'])
    # ### end Alembic commands ###
