"""add user to Category

Revision ID: b64992f51c51
Revises: 013c55fce6b3
Create Date: 2025-06-05 12:04:29.916890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64992f51c51'
down_revision: Union[str, None] = '013c55fce6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'category', ['user_id'])
    op.create_foreign_key(None, 'category', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
