"""correct errors with category: delete unique suer_id

Revision ID: d046227a1d3d
Revises: 4f0a5f703772
Create Date: 2025-06-05 21:37:38.067807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd046227a1d3d'
down_revision: Union[str, None] = '4f0a5f703772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_category_title', 'category', type_='unique')
    op.drop_constraint('transactions_user_id_key', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactions_user_id_key', 'transactions', ['user_id'])
    op.create_unique_constraint('uq_user_category_title', 'category', ['user_id', 'title'])
    # ### end Alembic commands ###
